# By default don't show group info as it is rarely important.
blocks:
  - permission
  - user
  - size
  - date
  - name

color:
  theme: custom

# Shorten the default date: 21-Mar-25 15:41.
date: +%e-%b-%y %R

sorting:
  dir-grouping: first
