[fisher]
plugins = [
    "catppuccin/fish",
    "jhillyerd/plugin-git",
    "jorgebucaran/autopair.fish",
    "jorgebucaran/fisher",
    "patrickf1/fzf.fish",
]

[homebrew]
brews = [
    "bat",
    "chezmoi",
    "choose-rust",
    "fd",
    "fish",
    "fzf",
    "git",
    "git-delta",
    "hyperfine",
    "lsd",
    "openssh",
    "rip2",
    "ripgrep",
    "sd",
    "starship",
    "vivid",
]
casks = ["1password", "discord", "font-jetbrains-mono", "kitty"]
