[homebrew]
brews = [
    "chezmoi",
    "choose-rust",
    "fd",
    "fish",
    "git",
    "hyperfine",
    "openssh",
    "rip2",
    "ripgrep",
    "sd",
]
casks = ["1password", "discord", "font-jetbrains-mono", "kitty"]
